[tool.poetry]
name = "a3d-cli"
version = "1.0.0"
description = "Axial3D CLI"
authors = ["Axial3D <opensource@axial3d.com>"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "6.2.4"
pytest-mock = "^3.6.1"
pytest-cov = "^2.12.1"
black = "^21.7b0"
isort = "^5.9.3"
unify = "^0.5"
pylint = "^2.9.6"
types-requests = "^2.25.6"
importlib-metadata = { version = "^4.6.4", markers = "python_version<='3.7'" }
typing-extensions = { version = "^3.10.0", markers = "python_version<='3.7'" }

[tool.poetry.scripts]
a3dcli = 'a3d_cli.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
profile = "black"
src_paths = ["a3d_cli/"]