
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-26T16:12:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "57c4d231239dc8df06232cf348118e96940f05f6",
 "version": "1.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
