[tool.poetry]
name = "shachbuildsystemtest"
version = "0.2.0"
description = ""
authors = ["Shacham Ginat <shacham.ginat@pagaya.com>"]

[tool.poetry.dependencies]
python = "^3.6.5"
setuptools = "^58.1.0"
wheel = "^0.37.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
