
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-27T13:29:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "040bbd29607ebcdf5bbff29ee6aabaf4bb8391a0",
 "version": "0.4.73"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
