
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T13:19:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1320f827eeaed2c712d51dce21b2b3be98cc0031",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
