from enum import Enum


class SensorType(str, Enum):
	TEMPERATURE = 'TEMPERATURE'
	PRESSURE = 'PRESSURE'
	PERCENTAGE = 'PERCENTAGE'
	COUNT = 'COUNT'
	DISTANCE = 'DISTANCE'
	TIMESTAMP = 'TIMESTAMP'
	IDENTIFIER = 'IDENTIFIER'
	STRING = 'STRING'
	HUMIDITY = 'HUMIDITY'
	CONCENTRATION = 'CONCENTRATION'
	LASER_POWER = 'LASER_POWER'


