"$schema" = "https://ghproxy.com/https://github.com/chenrz925/geyser/raw/main/src/geyser/schema.json"
engine = "serial"
[[tasks]]
reference = "geyser_lava.task.utility.IdProvider"
name = "id"
type = "task"

[tasks.inject]
title = "cifar10_resnet50"
[[tasks]]
reference = "geyser_lava.task.utility.PathProvider"
name = "path"
type = "task"

[tasks.rename]
path_provider = "path"
[[tasks]]
reference = "geyser_lava.task.utility.PathBuilder"
name = "dataset_root"
type = "functor"

[tasks.inject]
typename = "current"
subpaths = [ "dataset", "cifar10",]
[tasks.rename]
path = "dataset_root"
[[tasks]]
reference = "geyser_lava.profile._support.operator.ToTensor"
name = "vision_transform"
type = "functor"

[[tasks]]
reference = "geyser_lava.profile._support.operator.CifarUnflatten"
name = "train_dataset_params"
type = "functor"

[tasks.inject]
reference = "torchvision.datasets.cifar.CIFAR10"
train = true
download = true
[tasks.rebind]
root = "dataset_root"
[tasks.rename]
obj = "train_dataset_params"
[[tasks]]
reference = "geyser_lava.profile._support.operator.CifarUnflatten"
name = "validate_dataset_params"
type = "functor"

[tasks.inject]
reference = "torchvision.datasets.cifar.CIFAR10"
train = false
download = true
[tasks.rebind]
root = "dataset_root"
[tasks.rename]
obj = "validate_dataset_params"
[[tasks]]
reference = "geyser_lava.task.torch.common.DataLoaderProvider"
name = "train_loader"
type = "task"

[tasks.rebind]
dataset_params = "train_dataset_params"
[tasks.rename]
loader = "train_loader"
[tasks.inject.loader_params]
batch_size = 32
shuffle = true
[[tasks]]
reference = "geyser_lava.task.torch.common.DataLoaderProvider"
name = "validate_loader"
type = "task"

[tasks.rebind]
dataset_params = "validate_dataset_params"
[tasks.rename]
loader = "validate_loader"
[tasks.inject.loader_params]
batch_size = 32
shuffle = true
[[tasks]]
reference = "geyser_lava.task.torch.common.ModelProvider"
name = "model"
type = "task"

[tasks.inject.model_params]
reference = "torchvision.models.resnet.resnet50"
pretrained = false
progress = false
num_classes = 10
[[tasks]]
reference = "geyser_lava.task.torch.common.OptimizerProvider"
name = "optimizer"
type = "task"

[tasks.inject.optimizer_params]
reference = "torch.optim.adamw.AdamW"
[[tasks]]
reference = "geyser_lava.task.torch.common.LossProvider"
name = "loss"
type = "task"

[tasks.inject.loss_params]
reference = "torch.nn.modules.loss.CrossEntropyLoss"
[[tasks]]
reference = "geyser_lava.task.torch.trainer.SupervisedTrainer"
name = "trainer"
type = "task"

[tasks.inject]
max_epochs = 100
device = "cuda:0"
non_blocking = true
[[tasks.inject.metrics_params]]
reference = "ignite.metrics.accuracy.Accuracy"
name = "accuracy"

[tasks.inject.metrics_params.params]
device = "cuda:0"
[[tasks.inject.metrics_params]]
reference = "ignite.metrics.fbeta.Fbeta"
name = "f1macro"

[tasks.inject.metrics_params.params]
beta = 1

[flow]
name = "root"
type = "graph"
include = [ "id", "path", "dataset_root", "vision_transform", "train_dataset_params", "validate_dataset_params", "train_loader", "validate_loader", "model", "optimizer", "loss", "trainer",]
