# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "Client": "Client.ipynb",
    "DataSource": "Client.ipynb",
    "ProgressStatus": "Client.ipynb",
    "DataSource.pull": "Client.ipynb",
    "DataSource.head": "Client.ipynb",
    "Model": "Client.ipynb",
    "DataSource.train": "Client.ipynb",
    "Prediction": "Client.ipynb",
    "Model.evaluate": "Client.ipynb",
    "Model.predict": "Client.ipynb",
    "Prediction.to_pandas": "Client.ipynb",
    "DataSource.push": "Client.ipynb",
}

modules = ["client.py"]

doc_url = "//"

git_url = "https://gitlab.com/airt.ai/airt-client/tree/main/"


def custom_doc_links(name):
    return None
