[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = [".gitlab-ci.yml"]

[tool.coverage.run]
source = ["pupygrib"]

[tool.coverage.report]
fail_under = 93

[tool.isort]
profile = "black"
