VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('26')
VERSION_HOUR = int('17')
VERSION_MINUTE = int('19')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202109261719
version_date = '2021/09/26 17:19'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
