
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T22:02:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "532ec1ced95e10e386bc70af89112b4a0f88114e",
 "version": "0.27.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
