name: readthedocs
channels:
  - conda-forge
dependencies:
  - python=3.8
  - graph-tool==2.31
  - pip:
    - numba==0.50.1
    - numpy==1.18.4
    - pymatgen==2020.4.29
    - scipy==1.4.1
    - tqdm==4.46.0
