
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T16:40:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "159b002bde31d50588a914b7670f8a6900e5d34b",
 "version": "0.3.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
