
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-24T10:37:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6086face8e83eb6952afd949a352f181acae1e17",
 "version": "1.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
