
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T22:45:00-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "09fe8f2bf07bf1e07897f0b04a6d2dd90a369051",
 "version": "0.0.75"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
