[tool.poetry]
name = "poetry_1_conflict_svltv32"
version = "0.3.0"
description = ""
authors = ["sdfasdf"]

[tool.poetry.dependencies]
python = "^3.8"
poetry_2_conflict_svltv32 = "*"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
