#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['matops']

package_data = \
{'': ['*']}

setup(name='matops',
      version='0.1.1',
      description='Matrix Operations',
      author=None,
      author_email='Sarmad Gulzar <sarmadgulzar@hotmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
