
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T16:43:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "715ce17f8917d2bef078751468562a26e18f59c0",
 "version": "6.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
