
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T18:51:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "684ecd26c189732ede4fe178afc081808e126d13",
 "version": "1.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
