[tool.poetry]
name = "simplesimplestreams"
version = "0.1.0"
description = "simple simplestreams client"
authors = ["otariidae <otariidae@users.noreply.github.com>"]
license = "Apache-2.0"

homepage = "https://github.com/otariidae/simplesimplestreams"
repository = "https://github.com/otariidae/simplesimplestreams"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
types-requests = "^2.25.9"
black = "^21.9b0"
mypy = "^0.910"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
