
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-27T17:03:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8703ed32e4c4551b57dfca6b199207140f1a9e81",
 "version": "2021.09.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
