
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T15:34:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "55b3d15eef8ceda8ad07e1943ad4199afb73fe5c",
 "version": "0.4.75"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
