
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-23T18:56:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b55c57ca82e1b47253bb94d1bc1cc0befd463220",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
