# coding: utf-8

"""
    ARLAS Exploration API

    Explore the content of ARLAS collections  # noqa: E501

    OpenAPI spec version: 19.0.0
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import arlas_api_python
from arlas_api_python.models.extent import Extent  # noqa: E501
from arlas_api_python.rest import ApiException


class TestExtent(unittest.TestCase):
    """Extent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtent(self):
        """Test Extent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = arlas_api_python.models.extent.Extent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
