
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T17:40:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "05a183b880bc0311be849574792fc91a4225ec33",
 "version": "0.4.76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
