[tool.poetry]
name = "posca"
version = "0.1.0"
description = "a tiny portscanning app"
readme="README.md"
authors = ["Leo B. <bernerdoodle@outlook.de>"]

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4.0"}
pyfiglet = "^0.8.post1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.7"


[tool.poetry.scripts]
posca = "posca.main:app"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

