"""
    Delphix API Gateway

    Delphix API Gateway API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.engine import Engine
from delphix.api.gateway.model.errors import Errors
globals()['Engine'] = Engine
globals()['Errors'] = Errors
from delphix.api.gateway.model.list_engines_response import ListEnginesResponse


class TestListEnginesResponse(unittest.TestCase):
    """ListEnginesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEnginesResponse(self):
        """Test ListEnginesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListEnginesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
