"""
    Delphix API Gateway

    Delphix API Gateway API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.engine_user_mapping import EngineUserMapping


class TestEngineUserMapping(unittest.TestCase):
    """EngineUserMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEngineUserMapping(self):
        """Test EngineUserMapping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EngineUserMapping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
