repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args:
          - --profile
          - black
