
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T12:22:34-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "99e02b662e6fd1748bd295e28de40144c3a129b6",
 "version": "1.28.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
