
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T17:36:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2d61a9d765dae50175bfe8dc9c1eed06001acef",
 "version": "v0.2.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
