
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T14:58:09+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "efaeacaff38fe2d46bac7d8407e4e06819f2d82a",
 "version": "v1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
