def getHeader(version):
    if(version == 2.0):
        return ['version','sec_start','sec_end','gps_time','gps_date','gps_lat','gps_long','gps_alt','gps_lock','reserved','reserved','reserved','reserved','gas_temp','gas_rh','ANA pressure','unused','unused','unused','NH3 mox','NO2 mox','CO mox','O3 mox','NO2 ec','NH3 ec','NO2 ec_ar','NO2 ec_a','O3 ec_a','O3 ec_ar','CO ec','SO2 ec','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','d_temp','d_RH','reserved','reserved','reserved','reserved','reserved','ac_pump','ac_rate','ac_volt','reserved','reserved','reserved','reserved','reserved','std1.0','std2.5','std10','atm1.0','atm2.5','atm10','Count0.3','Count0.5','Count1.0','Count2.5','Count5.0','Count10','reserved','reserved','reserved','reserved','dyn_temp','xAccel','yAccel','zAccel','xGyro','yGyro','zGyro','xMag','yMag','zMag','rMag','reserved','reserved','mb_temp','mb_RH','mb_press','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','mb_battlevel','dyn_temp','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved']
    elif(version == 3.0):
        return ['version','sec_start','sec_end','gps_time','gps_date','gps_lat','gps_long','gps_alt','gps_lock','reserved','reserved','reserved','reserved','gas_temp','gas_rh','ANA pressure','unused','unused','unused','NH3 mox','NO2 mox','CO mox','O3 mox','NO2 ec','NH3 ec','NO2 ec_ar','NO2 ec_a','O3 ec_a','O3 ec_ar','CO ec','SO2 ec','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','d_temp','d_RH','reserved','reserved','reserved','reserved','reserved','ac_pump','ac_rate','ac_volt','reserved','reserved','reserved','reserved','reserved','std1.0','std2.5','std10','atm1.0','atm2.5','atm10','Count0.3','Count0.5','Count1.0','Count2.5','Count5.0','Count10','reserved','reserved','reserved','reserved','dyn_temp','xAccel','yAccel','zAccel','xGyro','yGyro','zGyro','xMag','yMag','zMag','rMag','reserved','reserved','mb_temp','mb_RH','mb_press','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','reserved','mb_battlevel','dyn_temp']

if __name__ == '__main__':
    #Something
    print("versionParsing")
    print(getHeader(2))