
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-26T16:32:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6eeffc864024f577542180a5eab3da9ef6482c1f",
 "version": "0.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
