
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-17T20:02:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e1e1ceb95decf14f9ecf8a3f913a688cb2a3ce1",
 "version": "1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
