[tool.poetry]
name = "fourwarder"
version = "0.1.0"
description = ""
authors = ["Giacomo Tagliabue <giacomo.tag@gmail.com>"]

[tool.poetry.scripts]
fourwarder = "fourwarder.main:run"

[tool.poetry.dependencies]
python = "^3.7"
docker = "^5.0.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
fourmat = "^0.10.1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target_version = ['py38']
