
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-01T11:57:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "78bd7d22a243b2e4673fd96f26d64626a838dfb2",
 "version": "v0.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
