
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T23:53:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "132cc7938a3640fda4d0dc1b0c50a355ec83d73d",
 "version": "0.0.76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
