
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-24T10:47:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9cf87698963d253d58049ddacfbd71a15aaf675",
 "version": "0.1.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
