
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T11:13:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "94e34155154a7dbf2c3f7d826a72d24fe62354cc",
 "version": "4.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
