#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='cyberpoweredpc',
      version='0.0.2',
      description='A cyber-powered PC builder for cyberpowerpc.com',
      author=None,
      author_email='DareDoes <me@daredoes.work>',
      url=None,
      py_modules=['cyberpoweredpc'],
     )
