# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: m1l0_services/dataservice/v1/data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='m1l0_services/dataservice/v1/data_service.proto',
  package='m1l0_services.dataservice.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/m1l0_services/dataservice/v1/data_service.proto\x12\x1cm1l0_services.dataservice.v1\"s\n\x19\x44\x61taServiceCollectRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x46\n\x06\x63onfig\x18\x02 \x01(\x0b\x32..m1l0_services.dataservice.v1.CollectionConfigR\x06\x63onfig\"\x88\x01\n\x10\x43ollectionConfig\x12\x16\n\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n\x07pattern\x18\x02 \x01(\tR\x07pattern\x12\x14\n\x05query\x18\x03 \x01(\tR\x05query\x12\x14\n\x05split\x18\x04 \x01(\tR\x05split\x12\x16\n\x06output\x18\x05 \x01(\tR\x06output\"0\n\x1a\x44\x61taServiceCollectResponse\x12\x12\n\x04\x62ody\x18\x01 \x01(\tR\x04\x62ody2\x90\x01\n\x0b\x44\x61taService\x12\x80\x01\n\x07\x43ollect\x12\x37.m1l0_services.dataservice.v1.DataServiceCollectRequest\x1a\x38.m1l0_services.dataservice.v1.DataServiceCollectResponse\"\x00\x30\x01\x62\x06proto3'
)




_DATASERVICECOLLECTREQUEST = _descriptor.Descriptor(
  name='DataServiceCollectRequest',
  full_name='m1l0_services.dataservice.v1.DataServiceCollectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='m1l0_services.dataservice.v1.DataServiceCollectRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='m1l0_services.dataservice.v1.DataServiceCollectRequest.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='config', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=196,
)


_COLLECTIONCONFIG = _descriptor.Descriptor(
  name='CollectionConfig',
  full_name='m1l0_services.dataservice.v1.CollectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='m1l0_services.dataservice.v1.CollectionConfig.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='source', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='m1l0_services.dataservice.v1.CollectionConfig.pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='pattern', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query', full_name='m1l0_services.dataservice.v1.CollectionConfig.query', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='query', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='split', full_name='m1l0_services.dataservice.v1.CollectionConfig.split', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='split', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='m1l0_services.dataservice.v1.CollectionConfig.output', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='output', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=335,
)


_DATASERVICECOLLECTRESPONSE = _descriptor.Descriptor(
  name='DataServiceCollectResponse',
  full_name='m1l0_services.dataservice.v1.DataServiceCollectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='m1l0_services.dataservice.v1.DataServiceCollectResponse.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='body', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=385,
)

_DATASERVICECOLLECTREQUEST.fields_by_name['config'].message_type = _COLLECTIONCONFIG
DESCRIPTOR.message_types_by_name['DataServiceCollectRequest'] = _DATASERVICECOLLECTREQUEST
DESCRIPTOR.message_types_by_name['CollectionConfig'] = _COLLECTIONCONFIG
DESCRIPTOR.message_types_by_name['DataServiceCollectResponse'] = _DATASERVICECOLLECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataServiceCollectRequest = _reflection.GeneratedProtocolMessageType('DataServiceCollectRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATASERVICECOLLECTREQUEST,
  '__module__' : 'm1l0_services.dataservice.v1.data_service_pb2'
  # @@protoc_insertion_point(class_scope:m1l0_services.dataservice.v1.DataServiceCollectRequest)
  })
_sym_db.RegisterMessage(DataServiceCollectRequest)

CollectionConfig = _reflection.GeneratedProtocolMessageType('CollectionConfig', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTIONCONFIG,
  '__module__' : 'm1l0_services.dataservice.v1.data_service_pb2'
  # @@protoc_insertion_point(class_scope:m1l0_services.dataservice.v1.CollectionConfig)
  })
_sym_db.RegisterMessage(CollectionConfig)

DataServiceCollectResponse = _reflection.GeneratedProtocolMessageType('DataServiceCollectResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATASERVICECOLLECTRESPONSE,
  '__module__' : 'm1l0_services.dataservice.v1.data_service_pb2'
  # @@protoc_insertion_point(class_scope:m1l0_services.dataservice.v1.DataServiceCollectResponse)
  })
_sym_db.RegisterMessage(DataServiceCollectResponse)



_DATASERVICE = _descriptor.ServiceDescriptor(
  name='DataService',
  full_name='m1l0_services.dataservice.v1.DataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=388,
  serialized_end=532,
  methods=[
  _descriptor.MethodDescriptor(
    name='Collect',
    full_name='m1l0_services.dataservice.v1.DataService.Collect',
    index=0,
    containing_service=None,
    input_type=_DATASERVICECOLLECTREQUEST,
    output_type=_DATASERVICECOLLECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASERVICE)

DESCRIPTOR.services_by_name['DataService'] = _DATASERVICE

# @@protoc_insertion_point(module_scope)
