
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-25T18:59:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "605d37ff5324b41672933df40293633f0e04bd4e",
 "version": "0.3.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
