
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-27T13:00:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a83a1ef82ece03b85751573e905ab13890f85fe2",
 "version": "0.7.1.post.dev62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
