
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T11:01:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fd0e677ecb721d348062e69bdc671714ce29e83",
 "version": "0.8.15a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
