[tool.poetry]
name = "caronte"
version = "1.0.0"
description = "A telegram bot that allows users to access groupchats using authentication."
authors = ["Lorenzo Balugani <lorenzo.balugani@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.5"
telepot = "^12.7"
SQLAlchemy = "^1.4.23"
psycopg2-binary = "^2.9.1"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
