
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T13:22:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "61cf2b7cdf805e5a24c11e50b0c586dac8c3598b",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
