[build-system]
requires = [
    "setuptools >= 42",
    "setuptools_scm[toml]>=3.4",
    "wheel"
    ]
build-backend = "setuptools.build_meta"

[tool.tox-constraints]
# Section is enough to enable

[tool.setuptools_scm]
# Section is enough to enable
