from enum import Enum

class observation_spaces(Enum):
    Ir = "Ir"
    IrSha1 = "IrSha1"
    BitcodeFile = "BitcodeFile"
    InstCount = "InstCount"
    Autophase = "Autophase"
    Programl = "Programl"
    ProgramlJson = "ProgramlJson"
    CpuInfo = "CpuInfo"
    IrInstructionCount = "IrInstructionCount"
    IrInstructionCountO0 = "IrInstructionCountO0"
    IrInstructionCountO3 = "IrInstructionCountO3"
    IrInstructionCountOz = "IrInstructionCountOz"
    ObjectTextSizeBytes = "ObjectTextSizeBytes"
    ObjectTextSizeO0 = "ObjectTextSizeO0"
    ObjectTextSizeO3 = "ObjectTextSizeO3"
    ObjectTextSizeOz = "ObjectTextSizeOz"
    IsBuildable = "IsBuildable"
    IsRunnable = "IsRunnable"
    Runtime = "Runtime"
    Buildtime = "Buildtime"
    Inst2vecPreprocessedText = "Inst2vecPreprocessedText"
    Inst2vecEmbeddingIndices = "Inst2vecEmbeddingIndices"
    Inst2vec = "Inst2vec"
    InstCountDict = "InstCountDict"
    InstCountNorm = "InstCountNorm"
    InstCountNormDict = "InstCountNormDict"
    AutophaseDict = "AutophaseDict"

class reward_spaces(Enum):
    IrInstructionCount = "IrInstructionCount"
    IrInstructionCountNorm = "IrInstructionCountNorm"
    IrInstructionCountO3 = "IrInstructionCountO3"
    IrInstructionCountOz = "IrInstructionCountOz"
    ObjectTextSizeBytes = "ObjectTextSizeBytes"
    ObjectTextSizeNorm = "ObjectTextSizeNorm"
    ObjectTextSizeO3 = "ObjectTextSizeO3"
    ObjectTextSizeOz = "ObjectTextSizeOz"
