language: python

python:
  - 3.6

env:
  - TOXENV=py36,codecov-travis
  - TOXENV=py36-pythran,codecov-travis CC=clang CXX=clang++

before_cache:
  - |
      coverage erase
      rm -f $HOME/.cache/pip/log/debug.log

cache:
    directories:
        - $HOME/.cache/pip

install:
    - pip install -U pip tox coverage

before_script:
    - |
      mkdir -p $HOME/.config/matplotlib
      echo 'backend      : TkAgg' > $HOME/.config/matplotlib/matplotlibrc
      echo -e "[pythran]\ncomplex_hook=True\n\n[compiler]\nCXX = clang++\nCC = clang\n" > $HOME/.pythranrc
      rm -rf $TRAVIS_BUILD_DIR/.tox

script:
    - tox -vv

after_failure:
    - cat $TRAVIS_BUILD_DIR/.tox/log/*.log

notifications:
  email: false
  irc: "chat.freenode.net#fluiddyn-tasks"
