[tool.poetry]
name = "legal-pre-processing"
version = "0.3.2"
description = "Pre processing tools for documents with legal content."
authors = [
    "Daniel Henrique Arruda Boeing <daniel.boeing@softplan.com.br>",
    "Israel Oliveira <israel.oliveira@softplan.com.br>"
    ]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/israel.oliveira.softplan/legal-pre-processing.git"
repository = "https://gitlab.com/israel.oliveira.softplan/legal-pre-processing.git"
keywords = ["legal", "text", "extract"]
include = [
    "CHANGELOG.md",
    "LICENSE",
    "legal_pre_processing/data/LegalRegExPatterns.json",
    "legal_pre_processing/data/LegalStopwords.json",
    "legal_pre_processing/data/TesauroRevisado.json"
    ]

[tool.poetry.dependencies]
python = ">=3.7"
Unidecode = ">=1.0"
PyMuPDF = ">=1.10"
nltk = ">=3.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = "^5.5"
pytest-cov = "^2.12.1"
locust = "^1.6.0"
flake8 = "^3.9.2"
black = "^21.7b0"
flake8-black = "^0.2.3"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.4.3"
safety = "^1.10.3"
pre-commit = "^2.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
