[tool.poetry]
name = "di"
version = "0.2.5"
description = "Autowiring dependency injection"
authors = ["Adrian Garcia Badaracco <adrian@adriangb.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<4"
anyio = "~3"

[tool.poetry.group.lint.dependencies]
black = ">=21.9b0,<22"
flake8 = "~3"
isort = "~5"
mypy = ">=v0.910"
pre-commit = "~2"

[tool.poetry.group.test.dependencies]
pytest = "~6"
pre-commit = "~2"
pytest-cov = { version = "~2", extras = ["toml"] }
pytest-sugar = "~0"
trio = "~0"

[tool.poetry.group.docs.dependencies]
mkdocs = "~1"
mkdocs-material = "~7"
mkautodoc = "~0"
mike = "~1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["di", "tests"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", '\.\.\.', "raise NotImplementedError"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
files = "di/**/*.py,tests/**/*.py,docs/**/*.py"
no_implicit_optional = true
allow_redefinition = false
implicit_reexport = false
warn_unreachable = true
