# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class OrganizationSSHCredentialsAddAPIPayload(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'credentials_name': 'str',
        'ssh_public_key': 'str'
    }

    attribute_map = {
        'credentials_name': 'credentials_name',
        'ssh_public_key': 'ssh_public_key'
    }

    def __init__(self, credentials_name=None, ssh_public_key=None, local_vars_configuration=None):  # noqa: E501
        """OrganizationSSHCredentialsAddAPIPayload - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._credentials_name = None
        self._ssh_public_key = None
        self.discriminator = None

        self.credentials_name = credentials_name
        self.ssh_public_key = ssh_public_key

    @property
    def credentials_name(self):
        """Gets the credentials_name of this OrganizationSSHCredentialsAddAPIPayload.  # noqa: E501


        :return: The credentials_name of this OrganizationSSHCredentialsAddAPIPayload.  # noqa: E501
        :rtype: str
        """
        return self._credentials_name

    @credentials_name.setter
    def credentials_name(self, credentials_name):
        """Sets the credentials_name of this OrganizationSSHCredentialsAddAPIPayload.


        :param credentials_name: The credentials_name of this OrganizationSSHCredentialsAddAPIPayload.  # noqa: E501
        :type credentials_name: str
        """
        if self.local_vars_configuration.client_side_validation and credentials_name is None:  # noqa: E501
            raise ValueError("Invalid value for `credentials_name`, must not be `None`")  # noqa: E501

        self._credentials_name = credentials_name

    @property
    def ssh_public_key(self):
        """Gets the ssh_public_key of this OrganizationSSHCredentialsAddAPIPayload.  # noqa: E501


        :return: The ssh_public_key of this OrganizationSSHCredentialsAddAPIPayload.  # noqa: E501
        :rtype: str
        """
        return self._ssh_public_key

    @ssh_public_key.setter
    def ssh_public_key(self, ssh_public_key):
        """Sets the ssh_public_key of this OrganizationSSHCredentialsAddAPIPayload.


        :param ssh_public_key: The ssh_public_key of this OrganizationSSHCredentialsAddAPIPayload.  # noqa: E501
        :type ssh_public_key: str
        """
        if self.local_vars_configuration.client_side_validation and ssh_public_key is None:  # noqa: E501
            raise ValueError("Invalid value for `ssh_public_key`, must not be `None`")  # noqa: E501

        self._ssh_public_key = ssh_public_key

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationSSHCredentialsAddAPIPayload):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganizationSSHCredentialsAddAPIPayload):
            return True

        return self.to_dict() != other.to_dict()
