
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-26T02:13:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c9ae862deed36bd7d498d912726a578a1fba82e",
 "version": "0.8.dev2139"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
