channels:
  - defaults
  - conda-forge
dependencies:
  - attrs>=19.2
  - click
  - eccodes>=2.20.0
  - mypy=0.812
  - nomkl
  - numpy
  - pandas=1.0.5
  - pytest-cov
  - python-eccodes>=2020.10.0
  - scipy
  - xarray>=0.15.0
