[tool.poetry]
name = "tor_project"
version = "0.1.0"
description = ""
authors = ["Ivan Yastrebov <easy.-quest@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = {extras = ["socks"], version = "^2.26.0"}
txtorcon = "^21.1.0"
Twisted = "^21.7.0"
ipaddress = "^1.0.23"
pygeoip = "^0.3.2"
"zope.interface" = "^5.4.0"
incremental = "^21.3.0"
Automat = "^20.2.0"
cryptography = "^3.4.8"
lxml = "^4.6.3"
bs4 = "^0.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
