[tool.poetry]
name = "django-dsfr"
version = "0.4.3"
description = "Integrate the French government Design System into a Django app"
authors = ["Sylvain Boissel <sylvain.boissel@dgcl.gouv.fr>"]
license = "MIT"

readme = "README.rst"
homepage = "https://github.com/entrepreneur-interet-general/django-dsfr"
repository = "https://github.com/entrepreneur-interet-general/django-dsfr"
keywords = ["django"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
]

packages = [
    { include = "dsfr" },
]

include = ["LICENSE", "README.rst", "dsfr/static/dsfr/dist/*/*.*" ]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.5"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = {version = "^21.7b0", allow-prereleases = true}
docutils = "^0.17.1"
coverage = "^5.5"
django-distill = "^2.9.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
