[tool.poetry]
name = "django_esbuild"
version = "0.1.0"
description = "Install and invoke esbuild from Python"
authors = ["Tim Kamanin <tim@timonweb.com>"]
homepage = "https://github.com/timonweb/django-esbuild"
readme = "README.md"
license = "MIT"

packages = [
    { include = "django_esbuild", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
esbuild = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
isort = "^5.9.3"
flake8 = "^3.9.2"
black = "^21.9b0"
Django = "^3.2.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
