
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T16:39:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cfe287019e7551fc52809da555aafe791258080",
 "version": "0.1.1.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
