
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-24T09:56:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d91cd05f2a8a4859f5271dd58c054e5000fee2bb",
 "version": "2535"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
