#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['msgoverhttp']

package_data = \
{'': ['*'], 'msgoverhttp': ['dist/*']}

setup(name='msgoverhttp',
      version='0.1.0',
      description="Let's find some podcasts!",
      author=None,
      author_email='xiao long <admin@coolink.pub>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
