# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ResponseVersionControlProject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'git_diff_file': 'ResponseFileMetadata',
        'git_diff_file_volume_id': 'int',
        'git_ref': 'str'
    }

    attribute_map = {
        'git_diff_file': 'git_diff_file',
        'git_diff_file_volume_id': 'git_diff_file_volume_id',
        'git_ref': 'git_ref'
    }

    def __init__(self, git_diff_file=None, git_diff_file_volume_id=None, git_ref=None, local_vars_configuration=None):  # noqa: E501
        """ResponseVersionControlProject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._git_diff_file = None
        self._git_diff_file_volume_id = None
        self._git_ref = None
        self.discriminator = None

        if git_diff_file is not None:
            self.git_diff_file = git_diff_file
        self.git_diff_file_volume_id = git_diff_file_volume_id
        if git_ref is not None:
            self.git_ref = git_ref

    @property
    def git_diff_file(self):
        """Gets the git_diff_file of this ResponseVersionControlProject.  # noqa: E501


        :return: The git_diff_file of this ResponseVersionControlProject.  # noqa: E501
        :rtype: ResponseFileMetadata
        """
        return self._git_diff_file

    @git_diff_file.setter
    def git_diff_file(self, git_diff_file):
        """Sets the git_diff_file of this ResponseVersionControlProject.


        :param git_diff_file: The git_diff_file of this ResponseVersionControlProject.  # noqa: E501
        :type git_diff_file: ResponseFileMetadata
        """

        self._git_diff_file = git_diff_file

    @property
    def git_diff_file_volume_id(self):
        """Gets the git_diff_file_volume_id of this ResponseVersionControlProject.  # noqa: E501


        :return: The git_diff_file_volume_id of this ResponseVersionControlProject.  # noqa: E501
        :rtype: int
        """
        return self._git_diff_file_volume_id

    @git_diff_file_volume_id.setter
    def git_diff_file_volume_id(self, git_diff_file_volume_id):
        """Sets the git_diff_file_volume_id of this ResponseVersionControlProject.


        :param git_diff_file_volume_id: The git_diff_file_volume_id of this ResponseVersionControlProject.  # noqa: E501
        :type git_diff_file_volume_id: int
        """

        self._git_diff_file_volume_id = git_diff_file_volume_id

    @property
    def git_ref(self):
        """Gets the git_ref of this ResponseVersionControlProject.  # noqa: E501


        :return: The git_ref of this ResponseVersionControlProject.  # noqa: E501
        :rtype: str
        """
        return self._git_ref

    @git_ref.setter
    def git_ref(self, git_ref):
        """Sets the git_ref of this ResponseVersionControlProject.


        :param git_ref: The git_ref of this ResponseVersionControlProject.  # noqa: E501
        :type git_ref: str
        """

        self._git_ref = git_ref

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseVersionControlProject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResponseVersionControlProject):
            return True

        return self.to_dict() != other.to_dict()
