[tool.poetry]
name = "pypstruct"
version = "0.1.2"
description = "PDB coordinates management python package"
authors = ["glaunay <pitooon@gmail.com>"]
license = "GPL"
repository="https://github.com/MMSB-MOBI/pypstruct"
classifiers=[
              "Intended Audience :: Science/Research",
              "License :: OSI Approved :: MIT License",
              "Programming Language :: Python :: 3",
              "Topic :: Scientific/Engineering :: Bio-Informatics",
              "Topic :: Software Development :: Libraries :: Python Modules",
              "Development Status :: 5 - Production/Stable"
       ]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
