[tool.poetry]
name = "comic_html_view_generator"
version = "0.2.2"
description = "HTML generator to view comic books"
authors = ["Leland Batey <lelandbatey@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Sphinx = "^4.1.2"
sphinx-rtd-theme = "^0.5.2"
twine = "^3.4.2"

[tool.poetry.scripts]
comic_html_view_generator = 'comic_html_view_generator.chvg:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
