
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T11:48:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8386b9eb926f804e4a941c9759d74f0d6245735",
 "version": "0.8.15a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
