
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T13:52:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "37e8242953815bfaca2b0401dec05758b189455c",
 "version": "1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
