
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T12:28:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ac658d4b7b7ee8e7bb2080a1168a17d18fcc121",
 "version": "2536"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
