# coding: utf-8

"""
    ARLAS Exploration API

    Explore the content of ARLAS collections  # noqa: E501

    OpenAPI spec version: 19.0.0
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Extent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'spatial': 'ExtentSpatial',
        'temporal': 'ExtentTemporal'
    }

    attribute_map = {
        'spatial': 'spatial',
        'temporal': 'temporal'
    }

    def __init__(self, spatial=None, temporal=None):  # noqa: E501
        """Extent - a model defined in Swagger"""  # noqa: E501

        self._spatial = None
        self._temporal = None
        self.discriminator = None

        self.spatial = spatial
        self.temporal = temporal

    @property
    def spatial(self):
        """Gets the spatial of this Extent.  # noqa: E501


        :return: The spatial of this Extent.  # noqa: E501
        :rtype: ExtentSpatial
        """
        return self._spatial

    @spatial.setter
    def spatial(self, spatial):
        """Sets the spatial of this Extent.


        :param spatial: The spatial of this Extent.  # noqa: E501
        :type: ExtentSpatial
        """
        if spatial is None:
            raise ValueError("Invalid value for `spatial`, must not be `None`")  # noqa: E501

        self._spatial = spatial

    @property
    def temporal(self):
        """Gets the temporal of this Extent.  # noqa: E501


        :return: The temporal of this Extent.  # noqa: E501
        :rtype: ExtentTemporal
        """
        return self._temporal

    @temporal.setter
    def temporal(self, temporal):
        """Sets the temporal of this Extent.


        :param temporal: The temporal of this Extent.  # noqa: E501
        :type: ExtentTemporal
        """
        if temporal is None:
            raise ValueError("Invalid value for `temporal`, must not be `None`")  # noqa: E501

        self._temporal = temporal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Extent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Extent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
