[tool.poetry]
name = "django-sass-finder"
version = "2.0.7"
description = "A Django finder that compiles Sass files"
readme = "README.md"
authors = [
    "Jesus Trujillo <trudev.professional@gmail.com>",
    "David Nugent <davidn@uniquode.io>"
]
repository = "https://github.com/Tru-Dev/django_sass_finder"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Framework :: Django",
    "Framework :: Django :: 3.0",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
]
keywords=[
    "django",
    "scss",
    "staticfiles",
]
packages = [
    { include = "django_sass_finder" }
]


[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.2"
libsass = "^0.21"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-pythonpath = "^0.7"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
