#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['codemate']

package_data = \
{'': ['*']}

install_requires = \
['black>=21.7b0,<22.0',
 'isort[requirements_deprecated_finder,pipfile_deprecated_finder]>=5.8.0,<6.0.0']

extras_require = \
{'dev': ['mypy==0.782',
         'flake8>=3.9.2,<4.0.0',
         'pre-commit>=2.12.1,<3.0.0',
         'pylint>=2.8.2,<3.0.0'],
 'doc': ['mkdocstrings>=0.15.2,<1.0.0',
         'mkdocs-material>=7.2.5,<8.0.0',
         'mkdocs-markdownextradata-plugin>=0.2.4,<1.0.0'],
 'test': ['pytest==5.4.3',
          'pytest-cov==2.10.0',
          'mypy==0.782',
          'flake8>=3.9.2,<4.0.0',
          'pylint>=2.8.2,<3.0.0']}

setup(name='codemate',
      version='0.3.0',
      description='Python syntax generator based on Object-Oriented Programing, type hints, and simplicity',
      author='Dor Abu',
      author_email='dor.abu@cyberproof.com',
      url='https://github.com/Cyberproof/codemate',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
