#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['cyberpoweredpc']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='cyberpoweredpc',
      version='0.0.1',
      description='A cyber-powered PC builder for cyberpowerpc.com',
      author=None,
      author_email='DareDoes <me@daredoes.work>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
     )
