[tool.poetry]
name = "mydata"
version = "0.1.0"
description = "Python SDK for myDATA"
authors = ["Paris Kasidiaris <paris@withlogic.co>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
