[tool.poetry]
name = "autosave"
version = "1.0.0.post1"
description = "Autosaving dictionary-like file objects"
readme = "README.md"
authors = ["Maximillian Strand <maximillian.strand@protonmail.com>"]
homepage = "https://gitlab.com/deepadmax/autosave"

[tool.poetry.dependencies]
python = "^3.9"
appdirs = "^1.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
