[tool.poetry]
name = "pyvorse"
version = "1.0.1"
description = "Simple essentials extension library of additions to vanilla python."
authors = ["Vladislav-Martian <me.as.martian@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
