[tool.poetry]
name = "pygoat"
description = 'Goat python module'
version = "0.1.1"
authors = [
  "Marcello Pontes <marcello@oncase.com.br>",
  "Anderson Moraes <anderson.moraes@oncase.com.br>",
]
readme = "README.md"
repository = "https://github.com/oncase/pygoat.git"

[tool.poetry.dependencies]
python = "~3.8.x"
fire = "0.4.0"
pandas = "1.2.3"
python-dotenv = "^0.15.0"
pyarrow = "^3.0.0"
google-cloud-secret-manager = "^2.3.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
autopep8 = "^1.5.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
goat = "pygoat.main:cli"
