[tool.poetry]
name = "eventy"
version = "3.1.0a2"
description = "Qotto/eventy"
license = "MIT"
authors = ["Qotto Dev Team <dev@qotto.net>"]
readme = "README.md"
#homepage
repository = "https://gitlab.com/qotto/oss/eventy"
documentation = "https://qotto.gitlab.io/oss/eventy"
#keywords
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 3 - Alpha",
    # Indicate who your project is intended for
    "Intended Audience :: Developers",
    # "Topic :: Software Development :: Build Tools",
    # Pick your license as you wish
    "License :: OSI Approved :: MIT License",
    # Specify the Python versions you support here. In particular, ensure
    # that you indicate whether you support Python 2, Python 3 or both.
    # These classifiers are *not* checked by 'pip install'. See instead
    # 'python_requires' below.
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
]
#packages
include = [
    "LICENSE",
]

#[tool.poetry.scripts]

[tool.poetry.dependencies]
python = "^3.7"
semver = ">=2"
coloredlogs = ">=15"
contextvars = ">=2"
avro-python3 = ">=1.9"

[tool.poetry.dev-dependencies]
environs = "*"
mypy = "*"
coverage = "*"
flake8 = "*"
sphinx = "*"
sphinxcontrib-plantuml = "*"
build = "*"
twine = "*"
setuptools = "*"
tox = "*"
pipfile = "*"
toml = "*"
sphinx-rtd-theme = "*"
pytest = "*"
sanic-testing = "*"
celery = "*"
sanic = "*"
django = "*"
confluent-kafka = "*"
types-requests = "*"
aiohttp = "*"

#[tool.poetry.extras]

#[tool.poetry.plugins]

[tool.poetry.urls]
"Qotto" = "http://www.qotto.net"
"Documentation" = "https://qotto.gitlab.io/oss/eventy"
"Source" = "https://gitlab.com/qotto/oss/eventy"
"Bug Reports" = "https://gitlab.com/qotto/oss/eventy/-/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
