
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-27T15:56:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8d1b8248a186b3c5f4764a07dd9aa73477fd5bb",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
