
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-24T10:25:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe9f7cf430d3d04a7a4d129f76208bd11d92ca25",
 "version": "2021.09.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
