
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T18:48:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6eb7182511bd0a4265079e30ed9ba63e2d9bf36a",
 "version": "v0.2.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
