[tool.poetry]
name = "ohcg"
version = "0.1.0"
description = "OpenAPI3 HTTP client generator"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.19.0"
jinja2 = "^3.0.1"
pydantic = {extras = ["email"], version = "^1.8.2"}
pydash = "^5.0.2"
typer = { extras = ["all"], version = "^0.4.0" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
ohcg = "ohcg.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
