
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T10:23:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f05d22634f3b81d00f6dc4df27afa8808c799be7",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
