[tool.poetry]
name = "ip_api_py"
version = "0.1.1"
description = "unoffical https://ip-api.com/ python API"
authors = ["dev <dev@qiyutech.tech>"]
license = "AGPL"

[tool.poetry.dependencies]
python = "^3.9"

requests = ">=2.26,<3"
pydantic = ">=1.7,<2"

[tool.poetry.dev-dependencies]
black = "*"
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
