VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('29')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('12')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202109291512
version_date = '2021/09/29 15:12'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
