[tool.poetry]
name = "digitex-bot-framework"
version = "1.0.3"
description = "Digitex Bot Framework"
authors = ["Sergey Bugaev <bugaevc@smartdec.com>", "Pavel Yushchenko <pyushchenko@digitexfutures.com>", "Andrii Lesyk <andrii@digitexfutures.com>"]
license = "GPL-3.0-or-later"
homepage = "https://digitex.io"
repository = "https://github.com/DigitexOfficial/bot-framework"

[tool.poetry.dependencies]
python = "^3.8"
digitex-engine-client = "^4.139.*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
