[tool.poetry]
name = "flexstore"
version = "0.0.3"
description = ""
authors = ["Dan Sikes <dansikes7@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
msgpack = "^1.0.2"
boto3 = "^1.17.84"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
