[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39']
skip-string-normalization = true

[tool.coverage.run]
command_line = "-m pytest"
source = ["data_validation"]

[tool.isort]
profile = 'black'
