# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: m1l0_services/dataservice/data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='m1l0_services/dataservice/data_service.proto',
  package='grpc.m1l0_services.dataservice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,m1l0_services/dataservice/data_service.proto\x12\x1egrpc.m1l0_services.dataservice\"e\n\x15\x44\x61taCollectionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12@\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x30.grpc.m1l0_services.dataservice.CollectionConfig\"a\n\x10\x43ollectionConfig\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07pattern\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\r\n\x05split\x18\x04 \x01(\t\x12\x0e\n\x06output\x18\x05 \x01(\t\"\x1e\n\x0e\x44\x61taServiceLog\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2\x83\x01\n\x0b\x44\x61taService\x12t\n\x07\x43ollect\x12\x35.grpc.m1l0_services.dataservice.DataCollectionRequest\x1a..grpc.m1l0_services.dataservice.DataServiceLog\"\x00\x30\x01\x62\x06proto3'
)




_DATACOLLECTIONREQUEST = _descriptor.Descriptor(
  name='DataCollectionRequest',
  full_name='grpc.m1l0_services.dataservice.DataCollectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.m1l0_services.dataservice.DataCollectionRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='grpc.m1l0_services.dataservice.DataCollectionRequest.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=181,
)


_COLLECTIONCONFIG = _descriptor.Descriptor(
  name='CollectionConfig',
  full_name='grpc.m1l0_services.dataservice.CollectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='grpc.m1l0_services.dataservice.CollectionConfig.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='grpc.m1l0_services.dataservice.CollectionConfig.pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query', full_name='grpc.m1l0_services.dataservice.CollectionConfig.query', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='split', full_name='grpc.m1l0_services.dataservice.CollectionConfig.split', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='grpc.m1l0_services.dataservice.CollectionConfig.output', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=280,
)


_DATASERVICELOG = _descriptor.Descriptor(
  name='DataServiceLog',
  full_name='grpc.m1l0_services.dataservice.DataServiceLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='grpc.m1l0_services.dataservice.DataServiceLog.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=312,
)

_DATACOLLECTIONREQUEST.fields_by_name['config'].message_type = _COLLECTIONCONFIG
DESCRIPTOR.message_types_by_name['DataCollectionRequest'] = _DATACOLLECTIONREQUEST
DESCRIPTOR.message_types_by_name['CollectionConfig'] = _COLLECTIONCONFIG
DESCRIPTOR.message_types_by_name['DataServiceLog'] = _DATASERVICELOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataCollectionRequest = _reflection.GeneratedProtocolMessageType('DataCollectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATACOLLECTIONREQUEST,
  '__module__' : 'm1l0_services.dataservice.data_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.m1l0_services.dataservice.DataCollectionRequest)
  })
_sym_db.RegisterMessage(DataCollectionRequest)

CollectionConfig = _reflection.GeneratedProtocolMessageType('CollectionConfig', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTIONCONFIG,
  '__module__' : 'm1l0_services.dataservice.data_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.m1l0_services.dataservice.CollectionConfig)
  })
_sym_db.RegisterMessage(CollectionConfig)

DataServiceLog = _reflection.GeneratedProtocolMessageType('DataServiceLog', (_message.Message,), {
  'DESCRIPTOR' : _DATASERVICELOG,
  '__module__' : 'm1l0_services.dataservice.data_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.m1l0_services.dataservice.DataServiceLog)
  })
_sym_db.RegisterMessage(DataServiceLog)



_DATASERVICE = _descriptor.ServiceDescriptor(
  name='DataService',
  full_name='grpc.m1l0_services.dataservice.DataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=315,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='Collect',
    full_name='grpc.m1l0_services.dataservice.DataService.Collect',
    index=0,
    containing_service=None,
    input_type=_DATACOLLECTIONREQUEST,
    output_type=_DATASERVICELOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASERVICE)

DESCRIPTOR.services_by_name['DataService'] = _DATASERVICE

# @@protoc_insertion_point(module_scope)
