VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('27')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('48')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202109272148
version_date = '2021/09/27 21:48'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
