[tool.poetry]
name = "mikro"
version = "0.1.15"
description = "images for arnheim"
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
license = "CC BY-NC 3.0"
packages = [{include = "mikro"}]

[tool.poetry.dependencies]
python = "^3.6"
herre = "^0.1.15"
docstring-parser = "^0.10"
inflection = "^0.5.1"
xarray = "^0.19.0"
s3fs = "^2021.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-aiohttp = "^0.3.0"
tox = "^3.24.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
