[tool.poetry]
name = "pybites-poetry-stub"
version = "0.2.0"
description = "Quick package to test automation of publishing to PyPI"
authors = ["Bob Belderbos <bobbelderbos@gmail.com>"]
license = "MIT"

packages = [
    {include = "mypackage"}
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
