[tool.poetry]
name = "nametract"
version = "1.1.1"
description = "Simple and stupid name extraction"
authors = ["keddad <keddad@yandex.ru>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/keddad/nametract"
repository = "https://github.com/keddad/nametract"
keywords = ["extractor", "names"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
