[tool.poetry]
name = "danilacasito-drutils"
version = "0.1.7"
description = "Some Utilities (BETA stage)"
authors = ["Daniel <danilacasito8@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
