[tool.poetry]
name = "ugoki"
version = "1.0.1"
description = "API Server to serve random gifs with support for public suggestions"
authors = ["Ceda EI <ceda_ei@webionite.com>"]
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://gitlab.com/ceda_ei/ugoki.git"
repository = "https://gitlab.com/ceda_ei/ugoki.git"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.68.1"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
SQLAlchemy = "^1.4.25"
pydantic = "^1.8.2"
python-multipart = "^0.0.5"

[tool.poetry.dev-dependencies]
aiofiles = "^0.7.0"

[tool.poetry.scripts]
ugoki-dev = "ugoki.cli:dev"
ugoki-prod = "ugoki.cli:prod"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
