[tool.poetry]
name = "capsule_downloader"
version = "1.0.1"
description = "A tool to help users easily download capsules from aotu.ai"
authors = ["Stephen Li <stephen@aotu.ai>"]
license = "Proprietary"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
requests = "^2.26.0"
wget = "^3.2"
beautifulsoup4 = "^4.10.0"
PyInquirer = "^1.0.3"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
capsule_downloader = 'capsule_downloader:main'
