# Generated by Django 3.2.6 on 2021-09-28 09:22

from django.db import migrations, models
import lab_orchestrator_lib_django_adapter.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_orchestrator_lib_django_adapter', '0002_auto_20210928_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerimagemodel',
            name='description',
            field=models.CharField(default='Description', max_length=128, validators=[lab_orchestrator_lib_django_adapter.models.not_empty]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labmodel',
            name='description',
            field=models.CharField(default='Description', max_length=128, validators=[lab_orchestrator_lib_django_adapter.models.not_empty]),
            preserve_default=False,
        ),
    ]
