[tool.poetry]
name = "flim-flam"
version = "0.1.2"
description = ""
authors = ["tlonny <t@lonny.io>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.18.49"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pylama = "^7.7.1"
pyflakes = "^2.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
flim-flam = 'flim_flam.cli:run'
