[tool.poetry]
name = "naparikro"
version = "0.1.5"
description = ""
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
license = "CC BY-NC 3.0"
packages = [{include = "naparikro"}]

[tool.poetry.dependencies]
python = "^3.8"
mikro = "^0.1.7"
arkitekt = "^0.1.18"

[tool.poetry.scripts]
mikroj = "naparikro.run:main"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-aiohttp = "^0.3.0"
tox = "^3.24.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
