VERSION_YEAR = 2021
VERSION_MONTH = int('09')
VERSION_DAY = int('25')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('55')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202109250955
version_date = '2021/09/25 09:55'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
