
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T13:29:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6248b1d31025a73f59912c81718d764b9610893",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
