# Generated by Django 3.1.12 on 2021-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubspot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hsoauth",
            name="stale",
            field=models.BooleanField(default=False),
        ),
    ]
