- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - sushy-tools-tempest-partition-bios-redfish-pxe
        - sushy-tools-tempest-partition-uefi-redfish-vmedia
    gate:
      jobs:
        - sushy-tools-tempest-partition-bios-redfish-pxe
        - sushy-tools-tempest-partition-uefi-redfish-vmedia
