# Generated by Django 2.2.17 on 2021-10-01 20:25

from django.db import migrations, models
import django.db.models.deletion
import django_old_records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_age', models.DurationField(blank=True, help_text='Maximum age of records to keep. Format: %d %H:%M:%S.%f', null=True)),
                ('export', models.BooleanField(default=False, help_text='Whether the records are going to be exported to a csv file before being deleted or not')),
                ('created_at_field', models.CharField(blank=True, help_text='DateTime field to be compared with current datetime to decide if record is old', max_length=100, null=True)),
                ('content_type', models.OneToOneField(limit_choices_to=django_old_records.models.limit_choices_to, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, validators=[django_old_records.models.validate_field])),
                ('value', models.CharField(max_length=100, validators=[django_old_records.models.validate_field_value])),
                ('max_age', models.DurationField()),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_old_records.ModelConfig')),
            ],
        ),
    ]
