repos:
- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black
    args: [--line-length=120]
- repo: git://github.com/doublify/pre-commit-isort
  rev: v4.3.0
  hooks:
  -   id: isort
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    args: ["--config=setup.cfg"]
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
- repo: local
  hooks:
  - id: gitchangelog
    language: system
    always_run: true
    pass_filenames: false
    name: Generate changelog
    entry: bash -c "gitchangelog > CHANGELOG.md"
    stages: [commit]
