name: publish

on:
  push:
    branches: [main, development]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.7"

            - name: Install dependencies
              run: |
                  make deps
            - name: Test w/ Pytest
              run: |
                  make test