[tool.poetry]
name = "drewcopytools"
version = "0.1.1"
description = "Utility code that I use in many of my python projects."
authors = ["Andrew Ritz <andrew.a.ritz@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
