
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-25T12:23:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "332b9f4af7152eff400d6b130eb9c8a24d36de51",
 "version": "0.3.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
