
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-27T16:34:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2adf5ef4f2885d84aa5190f4324644cf7d5f6673",
 "version": "0.3.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
