
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T10:50:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "372d4346f283ff5fc8f3a1ac16684a1c8a7ac22e",
 "version": "0.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
