
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-01T12:29:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9dbc9c2f00c052411ce3ff9befdcbfd84c031b3",
 "version": "0.1.1.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
