# Generated by Django 3.2.7 on 2021-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.GenericIPAddressField(verbose_name='REMOTE_ADDR')),
                ('path_info', models.TextField(verbose_name='PATH_INFO')),
                ('username', models.CharField(max_length=100, verbose_name='USERNAME')),
                ('password', models.CharField(max_length=100, verbose_name='PASSWORD')),
                ('csrf', models.CharField(max_length=100, verbose_name='CSRF')),
                ('until', models.DateTimeField(editable=False, verbose_name='UNTIL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Blocked',
                'verbose_name_plural': 'Blocked',
                'get_latest_by': 'until',
            },
        ),
    ]
