# Generated by Django 3.2.7 on 2021-09-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruteguard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocked',
            name='password',
        ),
        migrations.RemoveField(
            model_name='blocked',
            name='username',
        ),
    ]
