
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-01T13:30:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec92f64199e431b41aa6db976c7d32328333df4b",
 "version": "2537"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
