
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T20:47:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8795b7d46592deb0397da6a469645b07fcc9f6fe",
 "version": "1.6.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
