
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-30T16:14:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7edbc71b6856f56be7b27fcc79ec48fc0753472",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
