
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T16:31:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e44b748abb7ee4c5868207a2f7b5d7023778daa0",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
