
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-26T14:38:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a78d8dffa309cf750b0ac884382b573c71f8a4f",
 "version": "2021.09.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
