
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-24T11:15:52-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb3bd5864513134cc3801e2a06c47d2f8362f7b9",
 "version": "0.0.56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
