[tool.poetry]
name = "cyberpoweredpc"
version = "0.0.8"
description = "A cyber-powered PC builder for cyberpowerpc.com"
authors = ["DareDoes"]
license = "GPL-3.0-only"
readme = "README.md"

repository = "https://github.com/daredoes/cyberpoweredpc"
homepage = "https://github.com/daredoes/cyberpoweredpc"

[tool.poetry.dependencies]
python = "^3.9"
easygui = "0.98.2"
fire = "^0.4.0"
selenium = "3.141.0"
chromedriver-autoinstaller = "^0.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
