kind: ManifestVariable
id: "nmachine.telem.variable.strategy"
flat_key: "strategy"
title: "Storage Strategy"
level: "default_vars"
info: "Where the database lives. Either an in-cluster PVC (default) or an
arbitrary MongoDB database you manage yourself and point to."
default_value: "pvc"
input:
  kind: SelectInput
  options:
    - id: "pvc"
      title: "In-Cluster Managed Database - Plugin creates and manages
      Kubernetes resources (PVC, deployment, etc...)."
    - id: "managed_cloud"
      title: "NMachine Cloud - Secure remote database."
    - id: "self_managed"
      title: "Bring your own Database - You supply a URL to a MongoDB database."
validators:
  - operator: in
    check_against: ["pvc", "self_managed", "managed_cloud"]

---

kind: ManifestVariable
id: "nmachine.telem.variable.mongo.port"
flat_key: "mongo.port"
title: Self-managed Database Port
info: "Only set if using a self-managed database. Port on which
your database is running. Value will be ignored if strategy is PVC."
validators:
  - kind: FormatPredicate
    check_against: integer

---

kind: ManifestVariable
id: "nmachine.telem.variable.mongo.host"
flat_key: "mongo.host"
title: "Self-managed Database Host"
info: "Only set if using a self-managed database. Port on which
your database is running. Value will be ignored if strategy is PVC. For
 formatting information, like
how to include the password, refer to the MongoDB docs."
