
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T15:44:21+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "df7125450c30f41527d95726cd96e9c0696e0ddd",
 "version": "0.2.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
