
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T14:22:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "53a890aaa7d38cb273650f0a75e896b0d33d7471",
 "version": "1.27.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
