
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-25T17:14:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9efc2d8a7b3720685b8c63f6651e0ae6c1629868",
 "version": "0.3.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
