
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T23:18:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdefb1ae1a67b08ce48f40e53161293ddea7c062",
 "version": "0.3.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
