[tool.poetry]
name = "cyberpoweredpc"
version = "0.0.4"
description = "A cyber-powered PC builder for cyberpowerpc.com"
authors = ["DareDoes"]
license = "GNU GPL V3"

[tool.poetry.dependencies]
python = "^3.9"
fire = "^0.4.0"
selenium = "3.141.0"
chromedriver-autoinstaller = "^0.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
