#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mezcla']

package_data = \
{'': ['*'], 'mezcla': ['tests/*']}

setup(name='mezcla',
      version='1.1.0',
      description='Miscellaneous Python scripts developed over the course of several independent consulting projects. This also includes some code samples I adapted from publicly available source. (The code is not proprietary in nature. For example, it was not "borrowed" from proprietary source files, nor based on proprietary processes.)',
      author="Tomás O'Hara",
      author_email='tomasohara@gmail.com',
      url='https://github.com/tomasohara/mezcla',
      packages=packages,
      package_data=package_data,
     )
