---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.kube_name}}-app
spec:
  selector:
    matchLabels:
      app: {{cookiecutter.kube_name}}-app
  template:
    metadata:
      labels:
        app: {{cookiecutter.kube_name}}-app
    spec:
      containers:
        - name: app
          image: {{cookiecutter.project_name}}:latest
          {%- if cookiecutter.db_info.name == "sqlite" %}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              alembic upgrade head &&
              python -m {{cookiecutter.project_name }}
          {%- endif %}
          env:
            - name: {{cookiecutter.project_name | upper }}_HOST
              value: 0.0.0.0
            {%- if cookiecutter.db_info.name != "none" %}
            {%- if cookiecutter.db_info.name != "sqlite" %}
            - name: {{cookiecutter.project_name | upper }}_DB_HOST
              value: {{cookiecutter.kube_name}}-db-service
            {%- endif %}
            {%- endif %}
            {%- if cookiecutter.enable_redis == 'True' %}
            - name: {{cookiecutter.project_name | upper }}_REDIS_HOST
              value: {{cookiecutter.kube_name}}-redis-service
            {%- endif %}
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.kube_name}}-app-service
spec:
  selector:
    app: {{cookiecutter.kube_name}}-app
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{cookiecutter.kube_name}}-app
  labels:
    name: {{cookiecutter.kube_name}}-app
spec:
  rules:
    - host: {{ cookiecutter.kube_name }}.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{cookiecutter.kube_name}}-app-service
                port:
                  number: 80
