
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-29T10:44:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "305cf29e3738b0511d2e7fb87a57f6e00bd953b6",
 "version": "6.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
