
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-24T12:36:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "32912b462949bac259be6cc8f8afae86bf24d927",
 "version": "2021.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
