
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-24T10:40:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b63ad991fb376ce28704d87edf1646049892970b",
 "version": "1.8.5-dev.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
