
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T15:57:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c22f5bb636b7d4f59268297c0f6b83036f8b3889",
 "version": "0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
