
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-26T15:50:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6831335c0ca294dc2e16cb6ab3cb3be463e89d4c",
 "version": "4.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
