
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T15:34:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa4e6e851ea3f51faf70d43f0a78c2735a82bd7a",
 "version": "1.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
